_op1/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve
import debug_toolbar

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    re_path(r'^chaining/', include('smart_selects.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('main/', include('main.urls')),
    path('abidan/', include('abidan.urls')),
    path('tipitaka/', include('tipitaka.urls')),
    path('padanukkama/', include('padanukkama.urls')),
    path('setting/', include('setting.urls')),
    re_path(r'^.well-known/(.*)$', serve, {'document_root': '/var/www/html/_op1/.well-known/'}),
 ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\

tipitaka/urls.py
from django.urls import path

from . import views

urlpatterns = [
     path('digital-archive/', views.DigitalArchiveView.as_view(), name='digital_archive'),
     path('digital-archive/<int:pk>/', views.DigitalArchiveDetialsView.as_view(), name='digital_archive'),
     path('wordlist/', views.WordListView.as_view(), name='wordlist_master'),
     path('wordlist/<int:pk>/page-source', views.WordListPageSourceView.as_view(), name='wordlist_page_source'),
     path('toc/', views.TocView.as_view(), name='toc'),
     path('toc/<slug:slug>/structure/', views.StructureView.as_view(), name='structure'),
     path('toc/<slug:slug>/structure/<int:structure_id>/common-reference/',
          views.CommonReferenceSubformView.as_view(), name='common_reference_subform'),
     path('toc/<slug:slug>/structure/<int:structure_id>/common-reference/<int:pk>/',
          views.CommonReferenceSubformDetailView.as_view(), name='common_reference_subform_detail'),
     path('toc/<slug:slug>/structure/<int:structure_id>/common-reference/<int:pk>/delete',
          views.CommonReferenceSubformDeleteView.as_view(), name='common_reference_subform_delete'),
]

tipitaka/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from mptt.forms import TreeNodeMultipleChoiceField
from .models import Edition, Page, WordlistVersion, WordList, Structure, CommonReference

# query form (digital archive page)
class DigitalArchiveForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ["edition", "volume", "page_number", "content"]
        widgets = {
            'content': forms.TextInput(attrs={'rows': 1, 'max_length': 200, 'required': False})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['volume'].required = False
        self.fields['page_number'].required = False
        self.fields['content'].required = False


# page edit form (digital archive page)
class EditForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ("content",)
        widgets = {
            'content': forms.Textarea(attrs={'class': 'w3-input w3-border w3-round'}),
        }


class UpdWlAndPageForm(forms.ModelForm):
    word = forms.CharField(label=_("Word"), required=True, max_length=150)
    content = forms.CharField(label=_("Content"), required=True, widget=forms.Textarea(attrs={'class': 'w3-input w3-border w3-round'}))

    class Meta:
        model = WordList
        fields = ['word']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance:
            try:
                page = instance.page
                self.fields['content'].initial = page.content
            except Page.DoesNotExist:
                pass

    def save(self, commit=True):
        instance = super().save(commit=commit)
        if commit:
            try:
                page = instance.page
                page.content = self.cleaned_data['content']
                page.save()
            except Page.DoesNotExist:
                pass
        return instance


# wordlist generator form (wordlist generator page)
class WLGForm(forms.Form):
    edition = forms.ModelChoiceField(
        queryset=Edition.objects.filter(digitization=True),
        required=True
        )

class CommonReferenceForm(forms.ModelForm):
    class Meta:
        model = CommonReference
        fields = ['from_position', 'to_position',]
        widgets = {
            'from_position': forms.TextInput(attrs={'class': 'w3-input'}),
            'to_position': forms.TextInput(attrs={'class': 'w3-input'}),
        }


class WordlistFinderForm(forms.ModelForm):
    from_p = forms.CharField(label=_("From Position"), required=False,  max_length=20)
    to_p = forms.CharField(label=_("To Position"), required=False,  max_length=20)

    class Meta:
        model = WordList
        fields = ['edition', 'wordlist_version', 'volume', 'page', 'line_number']
        widgets = {
            'line_number': forms.NumberInput(attrs={'step': '1', 'min': '0'}),
        }
    # ----------------------------------------------------------------------------------------------------------------------------------------------
    def __init__(self, *args, **kwargs):
        self.structure_id = kwargs.pop('structure_id', None)
        super().__init__(*args, **kwargs)
        
        if self.structure_id:
            # get record from database (Structure)
            structure = get_object_or_404(Structure, id=self.structure_id)
            # ----------------------------------------------------------------
            # finding editions related to this structure
            # ----------------------------------------------------------------
            # Get all related WordlistVersions of this structure
            all_related_wordlist_versions = structure.table_of_content.wordlist_version.all()

            # Get all related Editions of these WordlistVersions
            all_related_editions = Edition.objects.filter(wordlistversion__in=all_related_wordlist_versions)

            # Get unique Editions based on code field
            self.fields['edition'].queryset = all_related_editions.distinct('code')

tipitaka/views.py
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.views import redirect_to_login
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic import TemplateView, DetailView
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin

from itertools import groupby
from braces.views import LoginRequiredMixin, SuperuserRequiredMixin

from utils.pali_char import *

from .models import Edition, Volume, Page, WordList, TableOfContent, Structure, CommonReference
from .tables import DigitalArchiveTable, WordlistMasterTable, WordlistMasterFilter, TocTable, StructureTable, StructureFilter, WordListTable, CommonReferenceTable
from .forms import DigitalArchiveForm, EditForm, UpdWlAndPageForm, WordlistFinderForm


# -----------------------------------------------------
# DigitalArchiveView
# -----------------------------------------------------
class DigitalArchiveView(LoginRequiredMixin, View): 
    def get(self, request):
        form = DigitalArchiveForm(request.GET)
        
        edition = request.GET.get('edition')
        volume = request.GET.get('volume', '')
        page_number = request.GET.get('page_number', '')
        content = request.GET.get('content', '')

        queryset = Page.objects.filter(
            edition=edition,
        )

        if volume:
            queryset = queryset.filter(volume=volume)
        if content:
            queryset = queryset.filter(content__contains=content)
        if page_number:
            queryset = queryset.filter(page_number=page_number)

        queryset = queryset.order_by('edition', 'volume', 'page_number')

        table = DigitalArchiveTable(queryset)
        table.paginate(page=request.GET.get("page", 1), per_page=25)
        total_rec = '{:,}'.format(table.page.paginator.count)

        return render(request, "tipitaka/digital_archive.html", {
            "form": form,
            'table': table,
            'total_rec': total_rec
        })


# -----------------------------------------------------
# DigitalArchiveDetialsView
# -----------------------------------------------------
class DigitalArchiveDetialsView(SuperuserRequiredMixin, UpdateView, SuccessMessageMixin):
    template_name = "tipitaka/digital_archive_details.html"
    model = Page
    form_class = EditForm
    success_message = _('Update successfully!')

    def handle_no_permission(self, request):
        messages.error(request, _('You do not have permission to access this page'))
        return redirect_to_login(request.get_full_path(), login_url=self.get_login_url(), redirect_field_name=self.get_redirect_field_name())

    def get_success_url(self):
        edition = int(self.request.GET.get('edition'))
        volume = self.request.GET.get('volume') or ''
        page_number = self.request.GET.get('page_number') or ''
        content = self.request.GET.get('content') or ''
        return '/tipitaka/digital-archive?edition=%s&volume=%s&page_number=%s&content=%s' %(edition, volume, page_number, content)



# -----------------------------------------------------
# WordListView
# -----------------------------------------------------
class WordListView(LoginRequiredMixin, SingleTableMixin, FilterView):
    model = WordList
    template_name = "tipitaka/wordlist_master.html"
    context_object_name  = "wordlist"
    table_class = WordlistMasterTable
    filterset_class = WordlistMasterFilter

    def get_context_data(self, **kwargs):
        context = super(WordListView, self).get_context_data(**kwargs)
        context["total_rec"] = '{:,}'.format(len(self.get_table().rows)) 
        return context



# -----------------------------------------------------
# WordListPageSourceView
# -----------------------------------------------------
class WordListPageSourceView(SuperuserRequiredMixin, UpdateView):
    model = WordList
    template_name = "tipitaka/wordlist_page_source.html"
    form_class = UpdWlAndPageForm
    success_url = reverse_lazy('wordlist_master')

    def handle_no_permission(self, request):
        messages.error(request, _('You do not have permission to access this page'))
        return redirect_to_login(request.get_full_path(), login_url=self.get_login_url(), redirect_field_name=self.get_redirect_field_name())

    def get_success_url(self):
        return self.request.path



# -----------------------------------------------------
# TABLE OF CONTENTS & COMMON REFERENCE
# -----------------------------------------------------
class TocView(LoginRequiredMixin, View):
    def get(self, request):
        queryset = TableOfContent.objects.all().order_by('code',)
        table = TocTable(queryset)
        table.paginate(page=request.GET.get("page", 1), per_page=25)
        total_rec = '{:,}'.format(table.page.paginator.count)

        return render(request, "tipitaka/toc.html", {
            'table': table,
            'total_rec': total_rec
        })
    


# -----------------------------------------------------
# StructureView
# -----------------------------------------------------
class StructureView(LoginRequiredMixin, SingleTableMixin, FilterView):
    model = Structure
    template_name = "tipitaka/structure.html"
    context_object_name  = "tocs"
    table_class = StructureTable
    filterset_class = StructureFilter
    
    def get_queryset(self):
        queryset = super().get_queryset()
        slug = self.kwargs.get('slug')
        table_of_content = get_object_or_404(TableOfContent, slug=slug)
        queryset = Structure.objects.filter(table_of_content=table_of_content)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(StructureView, self).get_context_data(**kwargs)
        context["total_rec"] = '{:,}'.format(len(self.get_table().rows)) 
        return context



# -----------------------------------------------------
# CommonReferenceSubformView
# -----------------------------------------------------
class CommonReferenceSubformView(SuperuserRequiredMixin, TemplateView):
    template_name = "tipitaka/common_reference_subform.html"

    def handle_no_permission(self, request):
        messages.error(request, _('You do not have permission to access this page'))
        return redirect_to_login(request.get_full_path(), login_url=self.get_login_url(), redirect_field_name=self.get_redirect_field_name())

    def get_initial_data(self, common_reference_id):
        if common_reference_id:
            common_reference = get_object_or_404(CommonReference, id=common_reference_id)
            parts = common_reference.from_position.split('-')
            edition = Edition.objects.filter(code=parts[0]).first()
            volume = Volume.objects.filter(Q(edition=edition) & Q(volume_number=int(parts[1]))).first() 
            page = Page.objects.filter(Q(edition=edition) & Q(volume=volume) & Q(page_number=int(parts[2]))).first()
            initial_data = {
                'edition': edition,
                'wordlist_version': common_reference.wordlist_version,
                'volume': volume,
                'page': page,
                'line_number': 0,
                'from_p': common_reference.from_position,
                'to_p': common_reference.to_position,
            }
            return initial_data
        else:
            return {
                'edition': '',
                'wordlist_version': '',
                'volume': '',
                'page': '',
                'line_number': 0,
                'from_p': '',
                'to_p': '',
            }

    def get_context_data(self, **kwargs):
        # context
        context = super().get_context_data(**kwargs)
        # get kwargs
        structure_id = self.kwargs['structure_id']
        common_reference_id = self.request.GET.get('common-reference')
        
        # get Structure & Common Reference related to this structure
        structure = get_object_or_404(Structure, id=structure_id)
        structure_tree = structure.get_children()

        # context data and form
        context['structure'] = structure
        context['structure_tree'] = structure_tree
        context['page'] = ''
        context['no_data_in_common_ref_table'] = ''
        context['error_message'] = ''

        # table
        context['wordlist_table'] = []
        context['common_ref_table'] = CommonReferenceTable(structure.commonreference_set.all())
        if len(context['common_ref_table'].rows) == 0:
            context['no_data_in_common_ref_table'] = _('No common references found')
        
        # form
        initial_data = self.get_initial_data(common_reference_id)
        context['WordlistFinderForm'] = WordlistFinderForm(initial=initial_data, structure_id=structure_id)

        # Accessing the fields
        fields = context['WordlistFinderForm'].fields
        context['edition_field'] = fields['edition']

        # return
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        # static variables
        SEARCH_SUBMIT = 'WordlistFinderForm_Search_Submit'
        ADD_OR_UPDATE = 'WordlistFinderForm_Add_or_Update'
        
        context = self.get_context_data(**kwargs)
        structure_id = self.kwargs['structure_id']
        form = WordlistFinderForm(request.POST, structure_id = structure_id )

        if form.is_valid():
            if SEARCH_SUBMIT in request.POST:
                page = Page.objects.get(id=request.POST['page'])
                wordlist_version = request.POST.get('wordlist_version')

tipitaka/templates/tipitaka/common_reference_subform.html
{% extends 'main/base.html' %}

{% load i18n static widget_tweaks %}

{% load render_table from django_tables2 %}

{% block extra_js %}
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
{% endblock %}

{% block extra_css %}
<style>
    .highlight-button {
        color: blue !important;
    }
</style>
{% endblock %}

{% block apptitle %}
    {% include 'tipitaka/include/title.html' %} : {% trans 'Table of Contents' %}・{% trans 'Structure' %}・{% trans 'Common Reference' %}
{% endblock %}

{% block apptitle_option %}
    <a class="w3-button w3-round-xlarge w3-hover-amber w3-display-right" onClick="javascript:history.go(-1);">{% trans "Back" %}</a>
{% endblock %}

{% block body %}

<div class="w3-cell-row w3-margin-top">
    <!-- sidebar -->
    <div id="sidebar" class="w3-cell" style="width:25%; padding-left:5px;">
        <div class="w3-row">
            <div><i class="fas fa-folder-tree"></i> {{ structure.table_of_content }}</div>
            <div><i class="fa fa-book"></i> {{ structure.title_number|default:"" }} {{ structure.title }}</div>

            {% if no_data_in_common_ref_table %}
                <p>{{ no_data_in_common_ref_table }}</p>
            {% else %}
                {% render_table common_ref_table %}
            {% endif %}

        </div>
        <!-- subfolder -->
        <div class="w3-row">
            {% load mptt_tags %}
            <ul class="root">
                {% recursetree structure_tree %}
                    <li>
                        <a href="{% url 'common_reference_subform' slug=node.table_of_content.slug structure_id=node.id %}" style="text-decoration: none">
                            {{ node.title_number|default:"" }} {{ node.title }}
                        </a>
                    </li>
                {% endrecursetree %}
            </ul>

        </div>
    </div>


    <div class="w3-container w3-cell">
        {% if edition_field.queryset.count %}
        <section>
            <!-- search form -->
            <form method="post">
                {% csrf_token %}
                {{ WordlistFinderForm.media.js }}
                <div class="w3-row-padding">
                    <div class="w3-col l8 m8 s12">
                        <label>{% trans WordlistFinderForm.edition.label_tag %}</label>
                        {{ WordlistFinderForm.edition|add_class:"w3-input" }}
                    </div>
                    <div class="w3-col l4 m4 s12">
                        <label>{% trans WordlistFinderForm.wordlist_version.label_tag %}</label>
                        {{ WordlistFinderForm.wordlist_version|add_class:"w3-input" }}
                    </div>
                </div>
                <div class="w3-row-padding">
                    <div class="w3-col l3 m3 s12">
                        <label>{% trans WordlistFinderForm.volume.label_tag %}</label>
                        {{ WordlistFinderForm.volume|add_class:"w3-input" }}   
                    </div>
                    <div class="w3-col l3 m3 s12">
                        <label>{% trans WordlistFinderForm.page.label_tag %}</label>
                        {{ WordlistFinderForm.page|add_class:"w3-input" }}
                    </div>
                    <div class="w3-col l3 m3 s12">
                        <label>{% trans WordlistFinderForm.line_number.label_tag %}</label>
                        {{ WordlistFinderForm.line_number|add_class:"w3-input" }}
                    </div>
                    <div class="w3-col l3 m3 s12 ">
                        <div class="w3-bar">
                            <button
                                type="submit"
                                name="WordlistFinderForm_Search_Submit"
                                class="w3-button w3-right w3-white w3-border w3-round-xlarge w3-hover-brown w3-margin">
                                    {% trans "Search" %}
                            </button>
                        </div>
                    </div>
                </div>
                <div class="w3-row-padding">
                    <div class="w3-col l3 m3 s12">
                        <label>{% trans WordlistFinderForm.from_p.label_tag %}</label>
                        {{ WordlistFinderForm.from_p|attr:"readonly"|add_class:"w3-input" }}   
                    </div> 
                    <div class="w3-col l3 m3 s12">
                        <label>{% trans WordlistFinderForm.to_p.label_tag %}</label>
                        {{ WordlistFinderForm.to_p|attr:"readonly"|add_class:"w3-input" }}   
                    </div>
                    <div class="w3-col l6 m6 s12 ">
                        <div class="w3-bar">
                            <button
                                type="submit"
                                id="add-reference-button"
                                name="WordlistFinderForm_Add_or_Update"
                                class="w3-button w3-right w3-white w3-border w3-round-xlarge w3-hover-brown w3-margin">
                                    {% trans "Add/Update" %}
                            </button>
                            <button
                                type="button"
                                onclick="resetValue()"
                                name="WordlistFinderForm_Reset"
                                class="w3-button w3-right w3-white w3-border w3-round-xlarge w3-hover-brown w3-margin">
                                    {% trans "Reset" %}
                            </button>
                        </div>
                    </div>
                </div>
            </form>

            {% if wordlist_table %}
                <div class="w3-bar w3-light-grey w3-margin-top">
                    <button class="w3-bar-item w3-button tablink w3-grey" onclick="openTabs(event,'overall')">{% trans 'Overall' %}</button>
                    <button class="w3-bar-item w3-button tablink" onclick="openTabs(event,'image_ref')">{% trans 'Image' %}</button>
                    <button class="w3-bar-item w3-button tablink" onclick="openTabs(event,'wordlist')">{% trans 'Wordlist' %}</button>
                    <button id="toggleSidebar" class="w3-bar-item w3-btn w3-right">
                        <i class="fa fa-toggle-on"></i>
                    </button>
                </div>
                
                <div id="overall" class="tab">
                    <div class="w3-cell-row">
                        <div class="w3-container w3-cell" style="width:50%; padding:0px !important">
                            <img class="mySlides w3-image" src="{{ page.image_ref }}">
                        </div>
                        <div class="w3-cell">
                            <div id="add-br">
                                <br>
                            </div>
                            <div class="w3-bar">
                                <button id="goDown" class="w3-btn w3-circle w3-ripple w3-white w3-border">
                                    <i class="fas fa-angle-down w3-small"></i>
                                </button>
                                <button id="goUp" class="w3-btn w3-circle w3-ripple w3-white w3-border">
                                    <i class="fas fa-angle-up w3-small"></i>
                                </button>
                            </div>
                                {% if wordlists %}
                                    {% for wordlist in wordlists_grouped %}
                                        {% for word in wordlist %}
                                            {% if forloop.first %}
                                                <span class="w3-tiny">{{ word.line_number }}:</span>
                                            {% endif %}
                                            <button
                                                id="{{ word.id }}"
                                                data-code="{{ word.code }}"
                                                class="word-id w3-btn w3-round-xlarge w3-tiny"
                                                style="border:none; background:none; cursor:pointer; padding:0px;"
                                                onclick="handlePadaButtonClick(this);"
                                            >
                                                {{ word.word }}
                                            </button>
                                        {% endfor %}
                                        <br>
                                    {% endfor %}
                                {% endif %}
                            </div>
                    </div>
                </div>
                <div id="image_ref" class="tab" style="display:none">
                    <img class="mySlides w3-image" src="{{ page.image_ref }}">
                </div>
                <div id="wordlist" class="tab" style="display:none">
                    {% render_table wordlist_table %} 
                </div>
            {% endif %}
        </section>
        {% endif %}
    </div>

</div>
{% endblock %}

{% block script%}
    <script>
        $(document).ready(function() {
            // set initial button state
            checkButtonState();

            // tooggle sidebar
            $( "#toggleSidebar" ).click(function(){
                $("#sidebar").toggle();
                
                // Toggle Font Awesome icon
                const icon = $(this).find("i");
                if (icon.hasClass("fa-toggle-on")) {
                    icon.removeClass("fa-toggle-on").addClass("fa-toggle-off");
                    
                    // Change class of buttons with class "word-id"
                    $(".word-id").removeClass("w3-tiny").addClass("w3-small");
                } else {
                    icon.removeClass("fa-toggle-off").addClass("fa-toggle-on");
                    
                    // Change class of buttons with class "word-id"
                    $(".word-id").removeClass("w3-small").addClass("w3-tiny");
                }
            });

            // adjustable top
            // กำหนดฟังก์ชันเมื่อกดปุ่มที่มี id ว่า "goDown"
            $('#goDown').click(function() {
                // เพิ่ม <br> ลงใน div ที่มี id ว่า "add-br" ทีละ 2 ตัว
                $('#add-br').append('<br><br>');
            });

            // กำหนดฟังก์ชันเมื่อกดปุ่มที่มี id ว่า "goUp"
            $('#goUp').click(function() {
                // หา <br> ล่าสุดและลบออก 2 ตัว
                $('#add-br').find('br:last').remove();
                $('#add-br').find('br:last').remove();
            });
        });

        function checkButtonState() {
            // get references to the input fields and the button
            var fromField = $("#id_from_p");
            var toField = $("#id_to_p");
            var addButton = $("button[name='WordlistFinderForm_Add_or_Update']");
        
            // check if both fields have values
            if (fromField.val() && toField.val()) {
                addButton.prop("disabled", false);
            } else {
                addButton.prop("disabled", true);
            }
        
            // Highlight buttons based on the values in fromField and toField
            var fromValue = fromField.val();
            var toValue = toField.val();

            $(".word-id").each(function() {
                var button = $(this);
                var dataCode = button.attr("data-code");
                if (dataCode === fromValue || dataCode === toValue) {
                    button.addClass("highlight-button");
                } else {
                    button.removeClass("highlight-button");
                }
            });
        }
        
        function openTabs(evt, tabName) {
            var i, x, tablinks;
            x = document.getElementsByClassName("tab");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablink");
            for (i = 0; i < x.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" w3-grey", "");
            }
            document.getElementById(tabName).style.display = "block";
            evt.currentTarget.className += " w3-grey";
        }

        function resetValue() {
            var destination_from = document.getElementById("id_from_p");
            var destination_to = document.getElementById("id_to_p");
            destination_from.value = '';
            destination_to.value = '';
            $("button[name='WordlistFinderForm_Add_or_Update']").prop("disabled", true);;
        };

        function copyValue(source, start) {
            if (start=='T') {
                var destination = document.getElementById("id_from_p");
                destination.value = source;
            } else {
                var destination = document.getElementById("id_to_p");
                destination.value = source;
            }
            checkButtonState();
        };

        function handlePadaButtonClick(button) {
            var from_p = document.getElementById("id_from_p");
            var to_p = document.getElementById("id_to_p");

            if (from_p.value !== "" && to_p.value !== "") {
                from_p.value = "";
                to_p.value = "";
                from_p.value = button.getAttribute("data-code");
            } else if (from_p.value === "" && to_p.value === "") {
                from_p.value = button.getAttribute("data-code");
            } else if (from_p.value !== "") {
                to_p.value = button.getAttribute("data-code");
            }
            checkButtonState();
        }
          
    </script>
{% endblock %}

tipitaka/templates/tipitaka/digital-archive.html
{% extends 'main/base.html' %}

{% load widget_tweaks %}
{% load render_table from django_tables2 %}
{% load i18n %}

{% block apptitle %}
    {% include 'tipitaka/include/title.html' %} : {% trans 'Digital Archived' %}
{% endblock %}

{% block body %}

    <form action="" method="get"
        
        class="w3-container w3-text-blue w3-padding"
        style="width:60%;margin:auto;">

        {{ form.media.js }}

        {% for field in form %}
            <p>
                <label>{% trans field.label_tag %}</label>
                {{ field|add_class:"w3-select" }}
            </p>
        {% endfor %}

        <button
            type="submit"
            class="w3-btn w3-black w3-hover-brown w3-round-xlarge">
                {% trans "Submit" %}
        </button>
    </form>


    {% render_table table %}


    <div class="w3-container w3-center">
        {% trans 'found' %} {{ total_rec }} {% trans 'record(s)' %} 
    </div>
{% endblock%}

tipitaka/templates/tipitaka/toc.html
{% extends 'main/base.html' %}

{% load widget_tweaks i18n %}

{% load render_table from django_tables2 %}

{% block apptitle %}
    {% include 'tipitaka/include/title.html' %} : {% trans 'Table of Contents' %}</h2>
{% endblock %}


{% block body %}
    {% render_table table %}

    <div class="w3-container w3-center">
        {% trans 'found' %} {{ total_rec }} {% trans 'record(s)' %} 
    </div>
{% endblock%}