_op1/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve
import debug_toolbar

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    re_path(r'^chaining/', include('smart_selects.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('main/', include('main.urls')),
    path('abidan/', include('abidan.urls')),
    path('tipitaka/', include('tipitaka.urls')),
    path('padanukkama/', include('padanukkama.urls')),
    path('setting/', include('setting.urls')),
    re_path(r'^.well-known/(.*)$', serve, {'document_root': '/var/www/html/_op1/.well-known/'}),
 ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\

setting/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # nama-saddamala
    path('nama-saddamala/', views.NamaSaddamalaView.as_view(), name='nama_saddamala'),
    path('nama-saddamala/create/', views.NamaSaddamalaCreateView.as_view(), name='nama_saddamala_create'),
    path('nama-saddamala/<int:pk>/update/', views.NamaSaddamalaUpdateView.as_view(), name='nama_saddamala_update'),
    path('nama-saddamala/<int:pk>/delete/', views.NamaSaddamalaDeleteView.as_view(), name='nama_saddamala_delete'),
    path('nama-saddamala/print/', views.NamaSaddamalaListView.as_view(), name='namasaddamala_list'),
    # noun-declension
    path('noun-declension/', views.NounDeclensionView.as_view(), name='noun_declension'),
    path('noun-declension/create/', views.NounDeclensionCreateView.as_view(), name='noun_declension_create'),
    path('noun-declension/<int:pk>/update/', views.NounDeclensionUpdateView.as_view(), name='noun_declension_update'),
    path('noun-declension/<int:pk>/delete/', views.NounDeclensionDeleteView.as_view(), name='noun_declension_delete'),
    # dhatu
    path('dhatu/', views.DhatuView.as_view(), name='dhatu'),
    path('dhatu/create/', views.DhatuCreateView.as_view(), name='dhatu_create'),
    path('dhatu/<int:pk>/update/', views.DhatuUpdateView.as_view(), name='dhatu_update'),
    path('dhatu/<int:pk>/delete/', views.DhatuDeleteView.as_view(), name='dhatu_delete'),
    # verb-conjugation
    path('verb-conjugation/', views.VerbConjugationView.as_view(), name='verb_conjugation'),
    path('verb-conjugation/create/', views.VerbConjugationCreateView.as_view(), name='verb_conjugation_create'),
    path('verb-conjugation/<int:pk>/update/', views.VerbConjugationUpdateView.as_view(), name='verb_conjugation_update'),
    path('verb-conjugation/<int:pk>/delete/', views.VerbConjugationDeleteView.as_view(), name='verb_conjugation_delete'),
]

padanukkama/models.py
from django.db import models
from django.db.models import Max, Q
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from django_editorjs import EditorJsField
from django_xworkflows import models as xwf_models
from mptt.models import MPTTModel, TreeForeignKey
from simple_history.models import HistoricalRecords
from smart_selects.db_fields import ChainedManyToManyField

from utils.pali_char import *

from tipitaka.models import WordlistVersion, TableOfContent, Structure, WordList
from .workflows import SaddaTranslationWorkflow

User = get_user_model()

# -----------------------------------------------------
# NamaType
# -----------------------------------------------------
class NamaType(models.Model):
    sequence = models.IntegerField(
        verbose_name=_("Sequence"))
    title = models.CharField(
        max_length=80,
        verbose_name=_("Title"))

    def __str__(self):
        return f"{self.title}"



# -----------------------------------------------------
# Linga
# -----------------------------------------------------
class Linga(models.Model):
    sequence = models.IntegerField(
        verbose_name=_("Sequence"))
    code = models.CharField(
        max_length=5,
        verbose_name=_("Code"))
    title = models.CharField(
        max_length=80,
        verbose_name=_("Title"))

    def __str__(self):
        return f"{self.code}"



# -----------------------------------------------------
# Karanta
# -----------------------------------------------------
class Karanta(models.Model):
    sequence = models.IntegerField(
        verbose_name=_("Sequence"))
    title = models.CharField(
        max_length=80,
        verbose_name=_("Title"))

    def __str__(self):
        return f"{self.title}"



# -----------------------------------------------------
# NamaSaddamala
# -----------------------------------------------------
class NamaSaddamala(models.Model):
    title = models.CharField(
        max_length=80,
        verbose_name=_("Title"))
    title_order = models.CharField(
        max_length=80,
        verbose_name=_("Title order"))
    title_code = models.CharField(
        max_length=80,
        verbose_name=_("Code"))
    nama_type = models.ForeignKey(
        "NamaType",
        null=True,
        blank=True,
        verbose_name=_("Type"),
        on_delete=models.SET_NULL) 
    linga = models.ForeignKey(
        "Linga",
        null=True,
        blank=True,
        verbose_name=_("Liṅga"),
        on_delete=models.SET_NULL) 
    karanta = models.ForeignKey(
        "Karanta",
        null=True,
        blank=True,
        verbose_name=_("Kāranta"),
        on_delete=models.SET_NULL) 
    nom_sg = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Paṭhamā Ekavacana"))
    nom_pl = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Paṭhamā Bahuvacana"))
    voc_sg = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Ālapana Ekavacana"))
    voc_pl = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Ālapana Bahuvacana"))
    acc_sg = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Dutiyā Ekavacana"))
    acc_pl = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Dutiyā Bahuvacana"))
    instr_sg = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Tatiyā Ekavacana"))
    instr_pl = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Tatiyā Bahuvacana"))
    dat_sg = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Catutthī Ekavacana"))
    dat_pl = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Catutthī Bahuvacana"))
    abl_sg = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Pañcamī Ekavacana"))
    abl_pl = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Pañcamī Bahuvacana"))
    gen_sg = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Chaṭṭhī Ekavacana"))
    gen_pl = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Chaṭṭhī Bahuvacana"))
    loc_sg = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Sattamī Ekavacana"))
    loc_pl = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_("Sattamī Bahuvacana"))
    popularity = models.IntegerField(
        default=0,
        null=True,
        blank=True,
        verbose_name=_("Popularity"))
    
    def __str__(self):
        return f"{self.title} ({self.linga})"

    def save(self, *args, **kwargs):
        self.title_order = encode(extract(clean(self.title)))
        super().save(*args, **kwargs)



# -----------------------------------------------------
# NounDeclension
# -----------------------------------------------------
class NounDeclension(models.Model):
    sequence = models.IntegerField(
        verbose_name=_("Sequence"))
    code = models.CharField(
        max_length=10,
        verbose_name=_("Code"))
    title = models.CharField(verbose_name=_("Title"))
    description = models.TextField(
        blank=True, null=True,
        verbose_name=_("Description"))
    ekavacana  = models.CharField(
        null=True, blank=True, 
        verbose_name=_("Meaning (Ekavacana)"))
    bahuvachana = models.CharField(
        null=True, blank=True, 
        verbose_name=_("Meaning (Bahuvacana)"))

    def __str__(self):
        return f"{self.code} : {self.title}"



# -----------------------------------------------------
# VerbConjugation
# -----------------------------------------------------
class VerbConjugation(models.Model):
    sequence   = models.IntegerField(default=0, verbose_name=_("Sequence"))
    title      = models.CharField(null=True, blank=True, verbose_name=_("Title"))
    description= models.CharField(null=True, blank=True, verbose_name=_("Description"))
    meaning    = models.CharField(null=True, blank=True, verbose_name=_("Meaning"))
    p1_para_sg = models.CharField(null=True, blank=True, verbose_name=_("Purisa 1 Parassapada Ekavacana"))
    p1_para_pl = models.CharField(null=True, blank=True, verbose_name=_("Purisa 1 Parassapada Bahuvacana"))
    p1_atta_sg = models.CharField(null=True, blank=True, verbose_name=_("Purisa 1 Attanopada Ekavacana"))
    p1_atta_pl = models.CharField(null=True, blank=True, verbose_name=_("Purisa 1 Attanopada Bahuvacana"))
    p2_para_sg = models.CharField(null=True, blank=True, verbose_name=_("Purisa 2 Parassapada Ekavacana"))
    p2_para_pl = models.CharField(null=True, blank=True, verbose_name=_("Purisa 2 Parassapada Bahuvacana"))
    p2_atta_sg = models.CharField(null=True, blank=True, verbose_name=_("Purisa 2 Attanopada Ekavacana"))
    p2_atta_pl = models.CharField(null=True, blank=True, verbose_name=_("Purisa 2 Attanopada Bahuvacana"))
    p3_para_sg = models.CharField(null=True, blank=True, verbose_name=_("Purisa 3 Parassapada Ekavacana"))
    p3_para_pl = models.CharField(null=True, blank=True, verbose_name=_("Purisa 3 Parassapada Bahuvacana"))
    p3_atta_sg = models.CharField(null=True, blank=True, verbose_name=_("Purisa 3 Attanopada Ekavacana"))
    p3_atta_pl = models.CharField(null=True, blank=True, verbose_name=_("Purisa 3 Attanopada Bahuvacana"))

    def __str__(self):
        return f"{self.title}"


# -----------------------------------------------------
# Language
# -----------------------------------------------------
class Language(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name=_("Language"))

    def __str__(self):
        return self.name



# -----------------------------------------------------
# Padanukkama
# -----------------------------------------------------
class Padanukkama(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name=_("Title"))
    about = models.TextField(
        blank=True,
        null=True, verbose_name=_("About"))
    publication = models.BooleanField(
        default=False,
        verbose_name=_("Publication"))
    collaborators = models.ManyToManyField(
        User,
        verbose_name=_("Collaborators"))
    target_languages = models.ManyToManyField(
        Language,
        verbose_name=_("Target Languages"))
    table_of_content = models.ForeignKey(
        TableOfContent,
        verbose_name=_("Table of Contents"),
        null=True,
        on_delete=models.CASCADE)
    wordlist_version = models.ManyToManyField(
        WordlistVersion,
        verbose_name=_("Wordlist Version"))
    structure = ChainedManyToManyField(
        Structure,
        chained_field="table_of_content",
        chained_model_field="table_of_content",
        verbose_name=_("Structure"),
        blank=True,
    )

    def __str__(self):
        return self.title



# -----------------------------------------------------
# Sadda
# -----------------------------------------------------
class Sadda(xwf_models.WorkflowEnabled, models.Model):
    SADDA_TYPE_CHOICES = [
        ('Nama', _('Nāma')),
        ('Akhyata', _('Akhyāta')),
        ('Byaya', _('Byaya')),
    ]
    padanukkama = models.ForeignKey(
        Padanukkama,
        on_delete=models.CASCADE,
        related_name='saddas',
        verbose_name=_("Padanukkama"))
    sadda = models.CharField(
        max_length=150,
        verbose_name=_("Sadda"))

setting/models.py
from django.db import models

# Create your models here.

setting/forms.py
from django import forms

from django.forms.widgets import CheckboxSelectMultiple
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

from django_select2.forms import *

from padanukkama.models import NamaSaddamala, Dhatu, Paccaya, \
                    AkhyataSaddamala, VerbConjugation, NounDeclension



# -----------------------------------------------------
# CheckboxMultipleSelect
# -----------------------------------------------------
class CheckboxMultipleSelect(forms.CheckboxSelectMultiple):
    def render(self, name, value, attrs=None, renderer=None):
        if value is None:
            value = []
        final_attrs = self.build_attrs(self.attrs, attrs)
        output = []
        id_ = final_attrs.get('id')
        for i, (option_value, option_label) in enumerate(self.choices):
            checkbox_id = f'{id_}_{i}'
            checked = option_value in value
            output.append(
                f'<div><label for="{checkbox_id}">'
                f'<input type="checkbox" class="structure-checkbox-select" name="{name}" value="{option_value}" id="{checkbox_id}"'
                f'{" checked" if checked else ""}>'
                f'{option_label}</label></div>'
            )
        return mark_safe('\n'.join(output))



# -----------------------------------------------------
# NamaSaddamalaForm
# -----------------------------------------------------
class NamaSaddamalaForm(forms.ModelForm):
    class Meta:
        model = NamaSaddamala
        exclude = ['title_order']



# -----------------------------------------------------
# DhatuForm
# -----------------------------------------------------
class DhatuForm(forms.ModelForm):
    paccaya = forms.ModelMultipleChoiceField(
        queryset=Paccaya.objects.all(),
        widget=CheckboxMultipleSelect(
            attrs={'class': 'structure-checkbox-select'}
        )
    )

    class Meta:
        model = Dhatu
        exclude = ['title_order', 'popularity']



# -----------------------------------------------------
# NounDeclensionForm
# -----------------------------------------------------
class NounDeclensionForm(forms.ModelForm):
    # Define the widget for ekavacana field
    ekavacana = forms.CharField(widget=forms.TextInput(attrs={'style': 'word-spacing: 10px;'}))
    # Define the widget for bahuvachana field
    bahuvachana = forms.CharField(widget=forms.TextInput(attrs={'style': 'word-spacing: 10px;'}))
    class Meta:
        # Specify the model to be used
        model = NounDeclension
        # Include all fields from the model
        fields = '__all__'



# -----------------------------------------------------
# VerbConjugationForm
# -----------------------------------------------------
class VerbConjugationForm(forms.ModelForm):
    class Meta:
        model = VerbConjugation
        fields = '__all__'




# -----------------------------------------------------
# AkhyataSaddamalaForm
# -----------------------------------------------------
class AkhyataSaddamalaForm(forms.ModelForm):
    class Meta:
        model = AkhyataSaddamala
        exclude = ['title_order']

setting/templates/setting/dhatu.html
{% extends 'main/base.html' %}

{% load widget_tweaks i18n %}

{% load render_table from django_tables2 %}

{% block apptitle %}
    {% include 'setting/include/title.html' %} : {% trans 'Nāmasaddapadamālā' %}
{% endblock %}

{% block apptitle_option %}
    <a href="{% url 'dhatu_create' %}" class="w3-button w3-round-xlarge w3-hover-yellow w3-display-right">{% trans "Add" %}</a>
{% endblock %}

{% block body %}
    {% if filter %}
        <form action="" method="get"
            class="w3-container w3-text-blue w3-padding"
            style="width:60%;margin:auto;">

            {% for field in filter.form %}
                <p>
                    <label>{% trans field.label_tag %}</label>
                    {{ field|add_class:"w3-input" }}
                </p>
            {% endfor %}

            <button
                type="submit"
                class="w3-button w3-dark-grey w3-hover-brown w3-round-xlarge">
                    {% trans "Submit" %}
            </button>
        </form>
    {% endif %}

    {% render_table table %}

    <div class="w3-container w3-center">
        {% trans 'found' %} {{ total_rec }} {% trans 'record(s)' %} 
    </div>
{% endblock%}

setting/templates/setting/dhatu_detail.html
{% extends 'main/base.html' %}

{% load widget_tweaks i18n %}

{% block apptitle %}
    {% include 'setting/include/title.html' %} : {% trans 'Dhātu' %}
    {% if url_name == 'dhatu_create' %}・{% trans 'Create' %}
    {% elif url_name == 'dhatu_update' %}・{% trans 'Update' %}
    {% elif url_name == 'dhatu_delete' %}・<span class="w3-text-red">{% trans 'Delete' %}</span>
    {% endif %}
{% endblock %}

{% block apptitle_option %}
    <a href="{% url 'dhatu' %}?{{ request.GET.urlencode }}"
        class="w3-button w3-round-xlarge w3-hover-amber w3-display-right">
        {% trans "Back" %}
    </a>
{% endblock %}

{% block body %}
    <!-- case delete -->
    {% if url_name == 'dhatu_delete' %}
        <div class="w3-container w3-padding"
             style="width:60%; margin:auto;">
            <div class="w3-row">
                <h4>{% trans 'Delete Dhātu' %}</h4>
                <p>{% trans 'Are you sure you want to delete the following Dhātu?' %}</p>
                <p><strong>{% trans 'Title' %}:</strong> {{ dhatu.title }}</p>
                <p><strong>{% trans 'Dhātugana' %}:</strong> {{ dhatu.dhatugana }}</p>
                <p><strong>{% trans 'Definition' %}:</strong> {{ dhatu.definition }}</p>
                <p><strong>{% trans 'Meaning' %}:</strong> {{ dhatu.meaning }}</p>
                <form method="post" action="{% url 'dhatu_delete' dhatu.pk %}">
                    {% csrf_token %}
                    <input type="submit" value="Confirm Delete" class="w3-button w3-round-xlarge w3-white w3-hover-red w3-border">
                </form>
            </div>
        </div>
    <!-- case add/update -->
    {% else %}
        <form action="" method="post"
            class="w3-container w3-padding"
            style="width:60%; margin:auto;">
            {% csrf_token %}

            {% for field in form %}
                <p>
                    <label>{% trans field.label_tag %}</label>
                    {{ field|add_class:"w3-input" }}
                </p>
            {% endfor %}

            <div class="w3-center">
                <div class="w3-bar">
                    {% if url_name == 'dhatu_update' %}
                        <a href="{% url 'dhatu_delete' object.pk %}"
                            class="w3-button w3-round-xlarge w3-white w3-border w3-hover-red w3-margin-right" 
                            style="width:150px">
                            {% trans 'Delete' %}
                        </a>
                    {% endif %}
                    <button
                        type="submit" style="width:150px"
                        class="w3-button w3-dark-grey w3-border w3-round-xlarge w3-hover-brown">
                        {% trans "Save" %}
                    </button>
                </div>
            </div>
        </form>
    {% endif %}
{% endblock %}

setting/templates/setting/nama_saddamala.html
{% extends 'main/base.html' %}

{% load widget_tweaks i18n %}

{% load render_table from django_tables2 %}

{% block apptitle %}
    {% include 'setting/include/title.html' %} : {% trans 'Nāmasaddapadamālā' %}
{% endblock %}

{% block apptitle_option %}
    <a href="{% url 'nama_saddamala_create' %}" class="w3-button w3-round-xlarge w3-hover-yellow w3-display-right">{% trans "Add" %}</a>
{% endblock %}

{% block body %}
    {% if filter %}
        <form action="" method="get"
            class="w3-container w3-text-blue w3-padding"
            style="width:60%;margin:auto;">

            {% for field in filter.form %}
                <p>
                    <label>{% trans field.label_tag %}</label>
                    {{ field|add_class:"w3-input" }}
                </p>
            {% endfor %}

            <button
                type="submit"
                class="w3-button w3-dark-grey w3-hover-brown w3-round-xlarge">
                    {% trans "Submit" %}
            </button>

            <a href="{% url 'namasaddamala_list' %}"
                class="w3-button w3-white w3-border w3-round-xlarge w3-hover-violet" 
                style="width:100px">
                {% trans 'Print' %}
            </a>
        </form>
    {% endif %}

    {% render_table table %}

    <div class="w3-container w3-center">
        {% trans 'found' %} {{ total_rec }} {% trans 'record(s)' %} 
    </div>
{% endblock%}

setting/templates/setting/nama_saddamala_list.html
{% extends 'main/blank.html' %}

{% load i18n %}

{% block body %}

{% block extra_css %}
<style>
    td {
        word-spacing: 10px;  /* ปรับระยะห่างระหว่างคำเป็น 10px */
    }    
</style>
{% endblock %}

{% for linga in lingas %}
    <h2>{{ linga.title }} ({{ linga.num_namasaddamala }} items)</h2>
    <table class="w3-table w3-bordered">
        <tr>
            <th style="width:20%">{% trans 'Title' %}</th>
            <th style="width:40%">{% trans 'Type' %}</th>
            <th style="width:20%">{% trans 'Liṅga' %}</th>
            <th style="width:20%">{% trans 'Kāranta' %}</th>
        </tr>
        {% for item in linga.namasaddamala_set.all %}
            <tr>
                <td style="width:20%">{{ item.title }}</td>
                <td style="width:40%">{{ item.nama_type }}</td>
                <td style="width:20%">{{ item.linga.title }}</td>
                <td style="width:20%">{{ item.karanta.title }}</td>
            </tr>
        {% endfor %}
    </table>
{% endfor %}

{% endblock %}

setting/templates/setting/nama_saddamala_list_full_details.html
{% extends 'main/blank.html' %}

{% load i18n %}

{% block body %}

{% block extra_css %}
<style>
    td {
        word-spacing: 10px;  /* ปรับระยะห่างระหว่างคำเป็น 10px */
    }    
</style>
{% endblock %}

{% for linga in lingas %}
    <h2>{{ linga.title }} ({{ linga.num_namasaddamala }} items)</h2>
        {% for item in linga.namasaddamala_set.all %}
            <table class="w3-table w3-bordered">
                <tr>
                    <th style="width:20%">{% trans 'Title' %}</th>
                    <th style="width:40%">{% trans 'Type' %}</th>
                    <th style="width:20%">{% trans 'Liṅga' %}</th>
                    <th style="width:20%">{% trans 'Kāranta' %}</th>
                </tr>
                <tr>
                    <td style="width:20%">{{ item.title }}</td>
                    <td style="width:40%">{{ item.nama_type }}</td>
                    <td style="width:20%">{{ item.linga.title }}</td>
                    <td style="width:20%">{{ item.karanta.title }}</td>
                </tr>
            </table>
            <table class="w3-table w3-striped w3-small">
                <tr>
                    <th style="width:40%">{% trans "Vibhatti" %}</th>
                    <th style="width:30%">{% trans "Ekavacana" %}</th>
                    <th style="width:30%">{% trans "Bahuvacana" %}</th>
                </tr>
                <tr>
                    <td>{% trans 'Paṭhamā' %}</td>
                    <td>{{ item.nom_sg|default_if_none:"-" }}</td>
                    <td>{{ item.nom_pl|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Ālapana' %}</td>
                    <td>{{ item.voc_sg|default_if_none:"-" }}</td>
                    <td>{{ item.voc_pl|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Dutiyā' %}</td>
                    <td>{{ item.acc_sg|default_if_none:"-" }}</td>
                    <td>{{ item.acc_pl|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Tatiyā' %}</td>
                    <td>{{ item.instr_sg|default_if_none:"-" }}</td>
                    <td>{{ item.instr_pl|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Catutthī' %}</td>
                    <td>{{ item.dat_sg|default_if_none:"-" }}</td>
                    <td>{{ item.dat_pl|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Pañcamī' %}</td>
                    <td>{{ item.abl_sg|default_if_none:"-" }}</td>
                    <td>{{ item.abl_pl|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Chaṭṭhī' %}</td>
                    <td>{{ item.gen_sg|default_if_none:"-" }}</td>
                    <td>{{ item.gen_pl|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Sattamī' %}</td>
                    <td>{{ item.loc_sg|default_if_none:"-" }}</td>
                    <td>{{ item.loc_pl|default_if_none:"-" }}</td>
                </tr>
            </table>

        {% endfor %}
{% endfor %}

{% endblock %}

setting/templates/setting/noun_declension.html
{% extends 'main/base.html' %}

{% load widget_tweaks i18n %}

{% load render_table from django_tables2 %}

{% block apptitle %}
    {% include 'setting/include/title.html' %} : {% trans 'Noun Declension' %}
{% endblock %}

{% block apptitle_option %}
    <a href="{% url 'noun_declension_create' %}" class="w3-button w3-round-xlarge w3-hover-yellow w3-display-right">{% trans "Add" %}</a>
{% endblock %}

{% block body %}
    {% if filter %}
        <form action="" method="get"
            class="w3-container w3-text-blue w3-padding"
            style="width:60%;margin:auto;">

            {% for field in filter.form %}
                <p>
                    <label>{% trans field.label_tag %}</label>
                    {{ field|add_class:"w3-input" }}
                </p>
            {% endfor %}

            <button
                type="submit"
                class="w3-button w3-dark-grey w3-hover-brown w3-round-xlarge">
                    {% trans "Submit" %}
            </button>
        </form>
    {% endif %}

    {% render_table table %}

    <div class="w3-container w3-center">
        {% trans 'found' %} {{ total_rec }} {% trans 'record(s)' %} 
    </div>
{% endblock %}

setting/templates/setting/verb_conjugation.html
{% extends 'main/base.html' %}

{% load widget_tweaks i18n %}

{% load render_table from django_tables2 %}

{% block apptitle %}
    {% include 'setting/include/title.html' %} : {% trans 'Verb Conjugation' %}
{% endblock %}

{% block apptitle_option %}
    <a href="{% url 'verb_conjugation_create' %}" class="w3-button w3-round-xlarge w3-hover-yellow w3-display-right">{% trans "Add" %}</a>
{% endblock %}

{% block body %}
    {% if filter %}
        <form action="" method="get"
            class="w3-container w3-text-blue w3-padding"
            style="width:60%;margin:auto;">

            {% for field in filter.form %}
                <p>
                    <label>{% trans field.label_tag %}</label>
                    {{ field|add_class:"w3-input" }}
                </p>
            {% endfor %}

            <button
                type="submit"
                class="w3-button w3-dark-grey w3-hover-brown w3-round-xlarge">
                    {% trans "Submit" %}
            </button>
        </form>
    {% endif %}

    {% render_table table %}

    <div class="w3-container w3-center">
        {% trans 'found' %} {{ total_rec }} {% trans 'record(s)' %} 
    </div>
{% endblock%}